name: Build & Install
on:
  push:
jobs:
  build:
    name: Build & Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install
        run: bun install
      - name: Build
        run: bun run build