name: Build & Deploy

on:
  push:
    branches: [main]
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Install & Build
    runs-on: ubuntu-latest
    environment: ci
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install
        run: bun install
      - name: Build
        run: bun run build
      - name: Create artifact
        run: |
          mkdir -p artifacts
          tar -czvf artifacts/github-pages.tar.gz -C ./dist .
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: github-pages
          path: artifacts/github-pages.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
