name: Release & Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    name: Build & Install
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      PUBLIC_BASE: /
      GALBE_REPO: git@github.com:pierre-cm/galbe.git
      GH_REPO: pierre-cm/galbe
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./dist
      - name: Install
        run: bun install
      - name: Build
        run: bun run build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
