name: Release & Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  release:
    name: Build, install & release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      PUBLIC_BASE: /
      GALBE_REPO: git@github.com:pierre-cm/galbe.git
      GH_REPO: pierre-cm/galbe
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Extract version from package.json
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Install
        run: bun install
      - name: Build
        run: bun run build
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}:${{ env.VERSION }},${{ steps.meta.outputs.tags }}:latest
          labels: ${{ steps.meta.outputs.labels }}
  # TODO: deploy. Use ssh to connect to remote server + docker pull latest image + docker swarm service
  # See docker swarm to ease depoyment!
  # deploy:
