name: Release & Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  release:
    name: Build, install & release
    runs-on: ubuntu-latest
    env:
      PUBLIC_BASE: /
      GALBE_REPO: git@github.com:pierre-cm/galbe.git
      GH_REPO: pierre-cm/galbe
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      COMMIT_SHA: ${{ github.sha::7 }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Extract version from package.json
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Install
        run: bun install
      - name: Build
        run: bun run build
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}-${{ env.COMMIT_SHA }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      - name: Deploy website
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_VPS_PRIVATE_KEY }}
          script: |
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}-${{ env.COMMIT_SHA }}
            docker service update --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}-${{ env.COMMIT_SHA }} website
